### ISSUE TITLE
typo in publisher name iceoryx-project-template/src/publisher.cpp

### ISSUE THREAD

**Issue by GaryMatthews** [eclipse-iceoryx/iceoryx-project-template#7]
--------------------------------------------------------|
-------------------------------------------------------\ /
constexpr const char APP_NAME[]{"publihser"};

constexpr const char APP_NAME[]{"publisher"};

## Required information
irrelevant

**Comment by mossmaurice** [comment]
@GaryMatthews Thanks for reporting the typo! Would you be interested to create a PR to fix it?
